ShoppingCart/Models/CartItem.cs
namespace ShoppingCart.Models
{
    public class CartItem
    {
        public int Id { get; set; }
        public int CartId { get; set; }
        public int BookId { get; set; }
        public int Quantity { get; set; }

        public virtual Cart Cart { get; set; }
        public virtual Book Book { get; set; }
    }
}

ShoppingCart/ViewModels/CartItemViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace ShoppingCart.ViewModels
{
    public class CartItemViewModel
    {
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }
        [JsonProperty(PropertyName = "cartId")]
        public int CartId { get; set; }
        [JsonProperty(PropertyName = "bookId")]
        public int BookId { get; set; }
        [JsonProperty(PropertyName = "quantity")]
        [Range(1,Int32.MaxValue,ErrorMessage = "数量必须大于0")]
        public int Quantity { get; set; }
        [JsonProperty(PropertyName = "book")]
        public virtual BookViewModel Book { get; set; }
    }
}

ShoppingCart/Controllers/Api/CartItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using ShoppingCart.Models;
using ShoppingCart.Services;
using ShoppingCart.ViewModels;

namespace ShoppingCart.Controllers.Api
{
    public class CartItemsController : ApiController
    {
        private readonly CartItemService _cartItemService=new CartItemService();

        public CartItemViewModel Post(CartItemViewModel cartItemViewModel)
        {
            var newCartItem =
                _cartItemService.AddToCart(AutoMapper.Mapper.Map<CartItemViewModel, CartItem>(cartItemViewModel));
            return AutoMapper.Mapper.Map<CartItem, CartItemViewModel>(newCartItem);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _cartItemService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShoppingCart/Controllers/CartsController.cs
using System.Web.Mvc;
using AutoMapper;
using ShoppingCart.Models;
using ShoppingCart.Services;
using ShoppingCart.ViewModels;

namespace ShoppingCart.Controllers
{
    public class CartsController : Controller
    {
        private readonly CartService _cartService=new CartService();

        [ChildActionOnly]
        public PartialViewResult Summary()
        {
            var cart = _cartService.GetBySessionId(HttpContext.Session.SessionID);
            return PartialView(Mapper.Map<Cart, CartViewModel>(cart));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _cartService.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Index()
        {
            throw new System.NotImplementedException();
        }
    }
}

ShoppingCart/Controllers/CategoriesController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using ShoppingCart.Models;
using ShoppingCart.Services;
using ShoppingCart.ViewModels;

namespace ShoppingCart.Controllers
{
    public class CategoriesController : Controller
    {
        private  readonly  CategoryService _categoryService=new CategoryService();
        
        [ChildActionOnly]
        public ActionResult Menu(int selectedcategoryid)
        {
            var categories = _categoryService.Get();
            ViewBag.SelectedCategoryId = selectedcategoryid;
            return PartialView(AutoMapper.Mapper.Map<List<Category>, List<CategoryViewModel>>(categories));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _categoryService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShoppingCart/Views/Shared/_CartItemForm.cshtml
@{
    var cartItem = new ShoppingCart.ViewModels.CartItemViewModel();
}

<template id="cart-item-form">
    <form class="center-block" data-bind="submit: upsertCartItem">
        <div class="form-group">
            <!-- ko if: cartItem.id === undefined -->
            @Html.LabelFor(m => cartItem.Quantity)
            <!-- /ko -->
            <div class="input-group form-group-sm">
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => cartItem.Quantity, new { data_bind = "textInput: cartItem.quantity", @class = "form-control" })
                    @Html.ValidationMessageFor(m => cartItem.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group" data-bind="isDirty: cartItem.quantity">
            <button type="submit" class="btn btn-primary" data-bind="visible: !sending(), text: cartItem.id === undefined ? 'Add To Cart' : 'Update'"></button>
        </div>
    </form>

    <div class="progress" data-bind="visible: sending">
        <div class="progress-bar progress-bar-info progress-bar-striped active"
             role="progressbar" aria-valuenow="100"
             aria-valuemin="0" aria-valuemax="100"
             style="width: 100%">
            <span class="sr-only"></span>
        </div>
    </div>
</template>

ShoppingCart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("购物车", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
                <div class="navbar-right" id="cart-details">
                    @Html.Action("Summary","Carts")
                </div>
            </div>
        </div>
    </div>
<div class="container body-content">
    <div class="well well-lg col-lg-3">
        @Html.Action("Menu","Categories",new {selectedCategoryId=ViewBag.SelectedCategoryId!=null?ViewBag.SelectedCategoryId:0})
    </div>
    <div class="col-lg-9">
        @RenderBody()
    </div>
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
    </footer>
</div>

    @Scripts.Render("~/bundles/shoppingCart")
    @RenderSection("scripts", required: false)
</body>
</html>